spring:
  application:
    name: application
  datasource:
    url: jdbc:mariadb://localhost:3306/db
    username: root
    password: sapassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true