spring:
  application:
    name: shopping-application
  datasource:
    url: jdbc:mariadb://localhost:3307/final_exam_bai03
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
